# Generated by Django 2.2.12 on 2020-09-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=10),
        ),
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.TextField(max_length=50),
        ),
    ]
