# Generated by Django 2.2.12 on 2020-09-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bids_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
